### PR TITLE
Slim image

### PR DESCRIPTION
**Pull request by sherzberg**
connects to Banno/infrastructure#385

This removes the vendored chronos code that was initially used to build the image. Our Dockerfile just wraps `mesoscloud/chronos:2.4.0-ubuntu-14.04` so we can push it to our internal registry

This also makes the imagew much smaller.

```
$ docker images | grep chronos
registry.banno-internal.com/chronos                                                          latest               6f1336c0532b        6 days ago          447 MB
registry.banno-internal.com/chronos                                                          2.4.0                17d4120475ff        9 months ago        1.102 GB
```

### CODE REVIEW

**Comment by sherzberg** [comment]
I also bumped the version to `2.4.1` for backwards compat with any environment that is currently running as the run args have changed. There is no real chronos `2.4.1`, but when that comes out, we can push over top of it since the run args should stay the same.

**Comment by DustinChaloupka** [comment]
👍

**Comment by adamdecaf** [comment]
👍

**Comment by sherzberg** [comment]
pushed

```
test_1         | 
test_1         | Chronos
test_1         |   chronos should be healthy
test_1         | 
test_1         | Finished in 4.21 seconds (files took 0.2904 seconds to load)
test_1         | 1 example, 0 failures
docker_test_1 exited with code 0
sherzberg@sherzberg-2~/workspace/banno/chronos-setup/docker[master]
$ rake push
docker push registry.banno-internal.com/chronos:2.4.1
The push refers to a repository [registry.banno-internal.com/chronos]
c8b8b2315485: Pushed 
d2596f7bc8d5: Pushed 
432e468b59fa: Pushed 
a599ca2ce248: Pushed 
cba62530f74a: Pushed 
d7a905e2ee84: Pushed 
a739ea00a948: Pushed 
470641744213: Pushed 
2.4.1: digest: sha256:9d0313189fb13374df254cf5fd96dae257bbf0a96ae0ddeb3b7c4c50d9e3ecde size: 8470
docker push registry.banno-internal.com/chronos:latest
The push refers to a repository [registry.banno-internal.com/chronos]
c8b8b2315485: Layer already exists 
d2596f7bc8d5: Layer already exists 
432e468b59fa: Layer already exists 
a599ca2ce248: Layer already exists 
cba62530f74a: Layer already exists 
d7a905e2ee84: Layer already exists 
a739ea00a948: Layer already exists 
470641744213: Layer already exists 
latest: digest: sha256:4c6dada1cac3bd7551502c58573f8e16326b47c756d26319571c68ec5c91311d size: 8471
```

**Pull request merged**
